run:
  timeout: 5m
  modules-download-mode: mod
  gotest: true

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - ineffassign

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers: false
      - name: indent-error-flow

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
      text: should have comment or be unexported
