name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  GOTOOLCHAIN: auto
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Cache Go build artifacts
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Verify gofmt
        run: |
          set -e
          CHANGED=$(gofmt -l $(find . -name '*.go' -not -path './.tools/*' -not -path './vendor/*'))
          if [ -n "$CHANGED" ]; then
            echo "Go files need formatting:" && echo "$CHANGED"
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61.0
          args: ./...

      - name: Run unit tests
        run: go test ./...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install frontend dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build frontend bundle
        run: pnpm --filter web build
      - name: Install Playwright browsers
        run: pnpm --filter web exec playwright install --with-deps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build service images (cached)
        uses: docker/bake-action@v4
        with:
          files: |
            deploy/docker-compose.yml
          targets: gateway crm wms analytics analytics-api
          set: |
            *.cache-from=type=gha,scope=asfp-pro
            *.cache-to=type=gha,scope=asfp-pro,mode=max
            *.output=type=docker

      - name: Copy environment file
        run: cp deploy/.env.example deploy/.env

      - name: Start postgres for migration checks
        run: docker compose --env-file deploy/.env -f deploy/docker-compose.yml up -d postgres

      - name: Wait for postgres
        run: |
          timeout 120 bash -c 'until docker compose --env-file deploy/.env -f deploy/docker-compose.yml exec -T postgres pg_isready -U asfp >/dev/null 2>&1; do sleep 2; done'

      - name: Verify DB migrations up/down
        env:
          DATABASE_URL: postgres://asfp:asfp123@localhost:5432/asfp?sslmode=disable
        run: |
          make migrate-core
          CORE_DOWN_TO=0 make migrate-core-down
          make migrate-core
          make migrate-crm
          CRM_DOWN_TO=0 make migrate-crm-down
          make migrate-crm
          make migrate-wms
          WMS_DOWN_TO=0 make migrate-wms-down
          make migrate-wms

      - name: Refresh demo data
        env:
          DATABASE_URL: postgres://asfp:asfp123@localhost:5432/asfp?sslmode=disable
        run: make refresh-demo

      - name: Validate demo dataset
        run: make check-demo

      - name: Refresh demo data
        env:
          DATABASE_URL: postgres://asfp:asfp123@localhost:5432/asfp?sslmode=disable
        run: make refresh-demo

      - name: Validate demo dataset
        run: make check-demo

      - name: Start dev stack
        run: docker compose --env-file deploy/.env -f deploy/docker-compose.yml up -d

      - name: Wait for services
        run: |
          timeout 180 bash -c 'until curl -sf http://localhost:8080/ready; do sleep 2; done'
          timeout 180 bash -c 'until curl -sf http://localhost:8081/ready; do sleep 2; done'
          timeout 180 bash -c 'until curl -sf http://localhost:8082/ready; do sleep 2; done'

      - name: Reset MinIO bucket
        run: bash scripts/minio-reset.sh

      - name: Run smoke tests
        env:
          SMOKE_GATEWAY_URL: http://localhost:8080
          SMOKE_CRM_URL: http://localhost:8081
          SMOKE_WMS_URL: http://localhost:8082
        run: make smoke

      - name: Run Playwright e2e tests
        env:
          E2E_GATEWAY_URL: http://localhost:8080
          E2E_CRM_URL: http://localhost:8081
          E2E_WMS_URL: http://localhost:8082
          E2E_GATEWAY_BASIC_AUTH: admin@asfp.pro:admin123
        run: pnpm --filter web exec playwright test

      - name: Tear down stack
        if: always()
        run: docker compose --env-file deploy/.env -f deploy/docker-compose.yml down -v
